#!/bin/bash
# This is a derivative work of https://gist.github.com/agnivade
#Oncorporating parts of: http://chris.beams.io/posts/git-commit/#seven-rules

comments=`awk '/^#/{a++}END{print a}' $1`
file_lines=`wc -l < $1 | xargs`
msg_lines=`expr $file_lines - $comments`

cnt=0
while IFS='' read -r line || [[ -n "$line" ]]; do
  cnt=$((cnt+1))
  length=${#line}
   if [ $cnt -eq 1 ]; then
	   if [ $length -eq 0 ]; then
		echo "Your subject cannot be empty."
		exit 1
	   fi
    # Checking if subject exceeds 50 characters
    if [ $length -gt 50 ]; then
      echo "Your subject line exceeds 50 characters."
      exit 1
    fi
    i=$(($length-1))
    last_char=${line:$i:1}
    # Last character must not have a punctuation
    if [[ ! $last_char =~ [0-9a-zA-Z] ]]; then
      echo "Last character of the subject line must not have punctuation."
      exit 1
    fi
    if [ $msg_lines -eq 1 ]; then
        exit 0
    fi
  elif [ $cnt -eq 2 ]; then
    # Subject must be followed by a blank line
    if [ $length -ne 0 ]; then
      echo "Your subject line follows a non-empty line. Subject lines should always be followed by a blank line."
      exit 1
    fi
  else
    # Any line in body must not exceed 72 characters
    if [ $length -gt 72 ]; then
      echo "The line \"$line\" exceeds 72 characters."
      exit 1
    fi
  fi
done < $1
